# It's recommended to change every "XeraTalist" to your servers name

tablist:
  header:
    - ""
    - "&4Xera&3Tablist"
    - ""
    - "&6This the default Tablist for XeraTablist"
    - ""
  footer:
    - ""
    - "%server_tps_1_colored%&3 tps — %bungee_total% players — %player_ping% ping —  %PlayTimes_uptime% uptime"
    - ""
    - "&7contact: Leee#2021"
    - "&7discussion: https://discord.gg/KgrrEQr"
    - "&7website: xera.ca"
    - "&7these are the only official xera websites and contacts."
    - ""