tablist:
  header:
    - ""
    - "&b6builders&36tools"
    - ""
    - "&6This the default Tablist ReloadCommand for LeeesTablist"
    - ""
  footer:
    - ""
    - "&7tps: <tps> &7ping: &f<ping> &7players: &f<players> &7uptime: &f<uptime>"
    - ""
    - "&7contact: nate@xera.ca"
    - "&7discussion: http://discord.6b6t.org"
    - "&7website: https://www.6b6t.org"
    - "&7These are the only official 6b6t websites and contacts"