# It's recommended to change every "SERVERNAME" to your servers name

tablist:
  header:
    - ""
    - "&bSERVERNAME"
    - ""
    - "&6This the default Tablist for XeraTablist"
    - ""
  footer:
    - ""
    - "&7tps: %tps% &7ping: &f%ping% &7players: &f%players% &7uptime: &f%uptime%"
    - ""
    - "&7contact: someone@example.com"
    - "&7discussion: http://discord.example.com"
    - "&7website: https://www.example.com"
    - "&7These are the only official SERVERNAME websites and contacts"