name: XeraTablist
version: 1.0.0
main: Xera.Tablist.XeraTablist
authors: [Nate Legault, Pistonmaster]
description: Most advanced tablist plugin for anarchy servers out there!
depend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: reload ReloadCommand
    usage: /tabrconfig
