name: XeraTablist
version: 2.1.0
main: Xera.Tablist.XeraTablist
authors: [Nate, Legault]
description: A Tablist plugin for 6b6t
softdepend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: reload ReloadCommand
    usage: /tabrconfig
