name: TabList
version: ${project.version}
main: org.anarchyplugins.tablist.TabListMain
authors: [Nate Legault, Pistonmaster, RemainingToast]
description: ${project.description}
softdepend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: Reload the config
    usage: /tabrconfig