name: TabList
version: ${project.version}
main: org.anarchyplugins.tablist.TabListMain
authors: [Nate Legault, Pistonmaster, RemainingToast]
description: ${project.description}
softdepend: [PlaceholderAPI]
commands:
  tabreload:
    description: Reload TAB
    usage: /tabreload