name: XeraTablist
version: ${project.version}
main: Xera.Tablist.XeraTablist
authors: [Nate Legault, Pistonmaster]
description: ${project.description}
softdepend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: Reload the config
    usage: /tabrconfig