name: LeeesTablist
version: 2.1.0
main: Leees.Tablist.Main
authors: [Nate, Legault]
description: A Tablist plugin for 6b6t
website: http://6b6t.org
softdepend: [PlaceholderAPI]
commands:
  tabrconfig:
    description: reload ReloadCommand
    usage: /tabrconfig
