tablist:
  name: "&b6builders&36tools"
  message: "&66b6t default tab message edit config.yml to change this"
  contact: "&7nate@xera.ca"
  discussion: "&7http://discord.6b6t.org"
  website: "&7https://www.6b6t.org/"
  official: "&7These are the only official 6b6t websites and contacts"
