name: LeeesTablist
version: 2.0.1
main: Leees.Tablist.Main
authors: [Nate, Legault]
description: A tablist plugin for 6b6t
website: http://6b6t.org
commands:
  tabrconfig:
    description: reload config
    usage: /tabrconfig
